name: Deploy to Heroku

on: [push]

jobs:
  Deploy-To-Heroku:
    runs-on: ubuntu-latest
    environment: heroku
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '17'
          cache: 'npm'
      - name: Install dependency
        run: npm install
      - name: Install packages dependency
        run: npx lerna bootstrap
      - run: npm test
      - name: Build client
        run: npm run build:client
      - name: Build and push Docker image to Heroku
        run: |
          sudo curl https://cli-assets.heroku.com/install.sh | sh
          HEROKU_API_KEY=${{ secrets.HEROKU_API_KEY }} heroku container:login
          HEROKU_API_KEY=${{ secrets.HEROKU_API_KEY }} heroku container:push --arg MONGODB_CONNECTION_URL=$MONGODB_CONNECTION_URL -a ${{ secrets.HEROKU_APP_NAME }} web
          HEROKU_API_KEY=${{ secrets.HEROKU_API_KEY }} heroku container:release -a ${{ secrets.HEROKU_APP_NAME }} web
